use_camera: False
use_lidar: True

image_height: 256
image_width: 256
latent_size: 32 # image_wifth // 8 
object_area_crop: 0.2

range_height: 256
range_width: 256 # use feature map crop instead of range crop

batch_size: 4
range_object_norm: True
range_object_norm_scale: 10
range_int_norm: True
num_workers_per_gpu: 4

classes:
  - car
  # - pedestrian
  # - traffic_cone
  # - truck
  # - construction_vehicle
  # - bus
  # - trailer
  # - barrier
  # - motorcycle
  # - bicycle

conditions:
  - ref_image
  - ref_bbox
  - ref_label

model:
  base_learning_rate: 8.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "inpaint"
    cond_stage_key: ${conditions}
    image_size: ${latent_size}
    channels: 8
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/median/object_pred_depth_L1_epoch
    u_cond_percent: 0.2
    scale_factor: 0.18215
    lidar_scale_factor: 0.18215
    use_ema: False
    use_camera: ${use_camera}
    use_lidar: ${use_lidar}
    range_object_norm: ${range_object_norm}
    range_object_norm_scale: ${range_object_norm_scale}
    range_int_norm: ${range_int_norm}

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 200 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: ${latent_size}
        in_channels: 9
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: False
        legacy: False
        add_conv_in_front_of_unet: False
        bbox_cond: True
        use_camera: ${use_camera}
        use_lidar: ${use_lidar}

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: ${image_height}
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    lidar_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: "checkpoints/image_vae.ckpt"
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: ${image_height}
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder
      params:
        conditions: ${conditions}

data:
  target: main.DataModuleFromConfig
  params:
      batch_size: ${batch_size}
      num_workers_per_gpu: ${num_workers_per_gpu}
      wrap: False
      train:
          target: ldm.data.nuscenes.NuScenesDataset
          params:
              state: train
              use_lidar: ${use_lidar}
              use_camera: ${use_camera}
              object_database_path: data/nuscenes/nuscenes_dbinfos_pbe_train.csv
              scene_database_path: data/nuscenes/nuscenes_scene_infos_pbe_train.pkl
              expand_mask_ratio: 0.1
              expand_ref_ratio: 0
              object_area_crop: ${object_area_crop}
              ref_aug: True
              ref_mode: same-ref
              image_height: ${image_height}
              image_width: ${image_width}
              range_height: ${range_height}
              range_width: ${range_width}
              object_classes: ${classes}
              random_range_crop: False
              min_lidar_points: 300
              range_object_norm: ${range_object_norm}
              range_object_norm_scale: ${range_object_norm_scale}
              range_int_norm: ${range_int_norm}
      validation:
          target: ldm.data.nuscenes.NuScenesDataset
          params:
              state: val
              use_lidar: ${use_lidar}
              use_camera: ${use_camera}
              object_database_path: data/nuscenes/nuscenes_dbinfos_pbe_val.csv
              scene_database_path: data/nuscenes/nuscenes_scene_infos_pbe_val.pkl
              expand_mask_ratio: 0.1
              expand_ref_ratio: 0
              object_area_crop: ${object_area_crop}
              ref_aug: True
              ref_mode: same-ref
              image_height: ${image_height}
              image_width: ${image_width}
              range_height: ${range_height}
              range_width: ${range_width}
              object_classes: ${classes}
              random_range_crop: False
              min_lidar_points: 300
              range_object_norm: ${range_object_norm}
              range_object_norm_scale: ${range_object_norm_scale}
              range_int_norm: ${range_int_norm}
      test:
          target: ldm.data.nuscenes.NuScenesDataset
          params:
              state: test
              use_lidar: ${use_lidar}
              use_camera: ${use_camera}
              object_database_path: data/nuscenes/nuscenes_dbinfos_pbe_val.csv
              scene_database_path: data/nuscenes/nuscenes_scene_infos_pbe_val.pkl
              expand_mask_ratio: 0.1
              expand_ref_ratio: 0
              object_area_crop: ${object_area_crop}
              ref_aug: False
              ref_mode: same-ref
              image_height: ${image_height}
              image_width: ${image_width}
              range_height: ${range_height}
              range_width: ${range_width}
              object_classes: ${classes}
              min_lidar_points: 300
              range_object_norm: ${range_object_norm}
              range_object_norm_scale: ${range_object_norm_scale}
              range_int_norm: ${range_int_norm}
      rotation_test:
          target: ldm.data.nuscenes.NuScenesDataset
          params:
              state: test
              use_lidar: ${use_lidar}
              use_camera: ${use_camera}
              object_database_path: data/nuscenes/nuscenes_dbinfos_pbe_val.csv
              scene_database_path: data/nuscenes/nuscenes_scene_infos_pbe_val.pkl
              expand_mask_ratio: 0.1
              expand_ref_ratio: 0
              object_area_crop: ${object_area_crop}
              prob_use_3d_edit_mask: 1
              ref_aug: False
              ref_mode: same-ref
              image_height: ${image_height}
              image_width: ${image_width}
              range_height: ${range_height}
              range_width: ${range_width}
              min_lidar_points: 300
              rot_every_angle: 30
              range_object_norm: ${range_object_norm}
              range_object_norm_scale: ${range_object_norm_scale}
              range_int_norm: ${range_int_norm}
              specific_scene: "06be0e3b665c44fa8d17d9f4770bdf9c"
              object_classes:
                - car

lightning:
  trainer:
    max_epochs: 40
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"